In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape, a.ndim, a.dtype, a.size

((3, 5), 2, dtype('int64'), 15)

In [8]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
x = np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
np.sin(x)

array([0.        , 0.24740396, 0.47942554, 0.68163876, 0.84147098,
       0.94898462, 0.99749499, 0.98398595, 0.90929743])

In [16]:
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[33,44],[45,67]])

In [17]:
np.multiply(a,b)

matrix([[ 33,  88],
        [135, 268]])

In [18]:
np.dot(a,b)

matrix([[123, 178],
        [279, 400]])