In [1]:
import numpy as np

In [2]:
A = np.mat([[0.2,0.3],[0.3,0.5]])
B = np.mat([[2,3],[4,5]])
print(A)
print(B)

[[0.2 0.3]
 [0.3 0.5]]
[[2 3]
 [4 5]]


In [3]:
s = A*np.linalg.inv(np.eye(2)-A)
s

matrix([[0.61290323, 0.96774194],
        [0.96774194, 1.58064516]])

In [4]:
X = B*np.linalg.inv(s)
X

matrix([[  8.,  -3.],
        [ 46., -25.]])

In [5]:
x = (B-B*A)*np.linalg.inv(A)
x

matrix([[  8.,  -3.],
        [ 46., -25.]])